export const DATABASE_ID = process.env.GITPOD_NEXT_PUBLIC_APPWRITE_DATABASE_ID!
export const COLLECTION_ID = process.env.GITPOD_NEXT_PUBLIC_APPWRITE_COLLECTION_ID!
export const BUCKET_ID = process.env.GITPOD_NEXT_PUBLIC_APPWRITE_BUCKET_ID!